import discord
from discord.ext import commands

client = commands.Bot(command_prefix = '.')

@client.event
async def on_ready():
    print('bot is ready to go :).')


@client.command()
async def about(ctx):
    await ctx.author.send('Hello I am CraftBot! I have all the crafting recipes you could ever need. You can use .list 1-5 to view a list of recipes and .craft with the name of the item for the recipe.')


@client.command()
async def craft(ctx, * ,choice):
    item = {
        'Wooden planks' : 'https://www.minecraftcrafting.info/imgs/craft_wood.gif',
        'Sticks' : 'https://www.minecraftcrafting.info/imgs/craft_stick.png',
        'Torches': 'https://www.minecraftcrafting.info/imgs/craft_torch.png',
        'Crafting Table' : 'https://www.minecraftcrafting.info/imgs/craft_workbench.png',
        'Furnace':'https://www.minecraftcrafting.info/imgs/craft_furnace.png',
        'Chest':'https://www.minecraftcrafting.info/imgs/craft_chest.png',
        'Ladders':'https://www.minecraftcrafting.info/imgs/new_craft_ladder.png',
        'Fence':'https://www.minecraftcrafting.info/imgs/craft_fence.gif',
        'Boat':'https://www.minecraftcrafting.info/imgs/craft_boat.png',
        'Wooden Slabs':'https://www.minecraftcrafting.info/imgs/craft_woodenslabs.gif',
        'Stone Slabs':'https://www.minecraftcrafting.info/imgs/craft_stoneslabs.gif',
        'Sign':'https://www.minecraftcrafting.info/imgs/craft_sign_new.png',
        'Doors':'https://www.minecraftcrafting.info/imgs/craft_doors.gif',
        'Wood':'https://www.minecraftcrafting.info/imgs/craft_wood2.png',
        'Glowstone':'https://www.minecraftcrafting.info/imgs/craft_glowstone.png',
        'Snow Block':'https://www.minecraftcrafting.info/imgs/craft_snow.png',
        'TNT':'https://www.minecraftcrafting.info/imgs/craft_tnt.png',
        'Clay Block':'https://www.minecraftcrafting.info/imgs/craft_clay.png',
        'Brick Block': 'https://www.minecraftcrafting.info/imgs/craft_brick.png',
        'Bookshelf':'https://www.minecraftcrafting.info/imgs/craft_bookshelf.png',
        'Sandstone Block':'https://www.minecraftcrafting.info/imgs/craft_sandstone.png',
        'Smooth Sandstone':'https://www.minecraftcrafting.info/imgs/craft_smoothsandstone.png',
        'Decorative Sandstone':'https://www.minecraftcrafting.info/imgs/craft_decorativesandstonw.png',
        'Note Block':'https://www.minecraftcrafting.info/imgs/craft_noteblock.png',
        'Jack-O Lantern':'https://www.minecraftcrafting.info/imgs/craft_jackolantern_new.png',
        'Lapis Lazuli Block':'https://www.minecraftcrafting.info/imgs/craft_lapis.png',
        'Diamond Block':'https://www.minecraftcrafting.info/imgs/craft_diamondblock.jpg',
        'Gold Block':'https://www.minecraftcrafting.info/imgs/craft_goldblock.jpg',
        'Iron Block':'https://www.minecraftcrafting.info/imgs/craft_ironblock.jpg',
        'Emerald Block':'https://www.minecraftcrafting.info/imgs/craft_emeraldblock.png',
        'Coal Block':'https://www.minecraftcrafting.info/imgs/craft_coalblock.png',
        'Stone Brick':'https://www.minecraftcrafting.info/imgs/craft_stonebrick.png',
        'Wooden Stairs':'https://www.minecraftcrafting.info/imgs/craft_woodenstairs.gif',
        'Stone Stairs':'https://www.minecraftcrafting.info/imgs/craft_stonestairs.gif',
        'Cobblestone Wall':'https://www.minecraftcrafting.info/imgs/craft_cobblestonewall.gif',
        'Block of Redstone':'https://www.minecraftcrafting.info/imgs/craft_blockofredstone.png',
        'Nether Brick':'https://www.minecraftcrafting.info/imgs/craft_netherbrick.png',
        'Block of Quartz':'https://www.minecraftcrafting.info/imgs/craft_blockofquartz.png',
        'Chiseled Quartz Block':'https://www.minecraftcrafting.info/imgs/craft_chiseledquartzblock.png',
        'Pillar Quartz Block':'https://www.minecraftcrafting.info/imgs/craft_pillarquartzblock.png',
        'Stained Clay':'https://www.minecraftcrafting.info/imgs/craft_stainedclay.gif',
        'Hay Bale':'https://www.minecraftcrafting.info/imgs/craft_haybale.png',
        'Granite':'https://www.minecraftcrafting.info/imgs/craft_granite.png',
        'Andesite':'https://www.minecraftcrafting.info/imgs/craft_andesite.png',
        'Diorite':'https://www.minecraftcrafting.info/imgs/craft_diorite.png',
        'Polished Granite':'https://www.minecraftcrafting.info/imgs/craft_polishedgranite.png',
        'Polished Andesite':'https://www.minecraftcrafting.info/imgs/craft_polishedandesite.png',
        'Polished Diorite':'https://www.minecraftcrafting.info/imgs/craft_polisheddiorite.png',
        'Prismarine':'https://www.minecraftcrafting.info/imgs/craft_prismarine.png',
        'Prismarine Bricks':'https://www.minecraftcrafting.info/imgs/craft_prismarinebricks.png',
        'Dark Prismarine':'https://www.minecraftcrafting.info/imgs/craft_darkprismarine.png',
        'Sea Lantern':'https://www.minecraftcrafting.info/imgs/craft_sealantern.png',
        'Coarse Dirt':'https://www.minecraftcrafting.info/imgs/craft_coarsedirt.png',
        'Slime Block':'https://www.minecraftcrafting.info/imgs/craft_slimeblock.png',
        'Moss Stone':'https://www.minecraftcrafting.info/imgs/craft_mossstone.png',
        'Mossy Stone Brick':'https://www.minecraftcrafting.info/imgs/craft_mossystonebrick.png',
        'Chiseled Stone Brick':'https://www.minecraftcrafting.info/imgs/craft_chiseledstonebrick.png',
        'Red Sandstone':'https://www.minecraftcrafting.info/imgs/craft_redsandstone.png',
        'Smooth Red Sandstone':'https://www.minecraftcrafting.info/imgs/craft_smoothredsandstone.png',
        'Chiseled Red Sandstone':'https://www.minecraftcrafting.info/imgs/craft_chiseledredsandstone.png',
        'Purpur Block':'https://www.minecraftcrafting.info/imgs/craft_purpurblock.png',
        'Purpur Pillar':'https://www.minecraftcrafting.info/imgs/craft_purpurpillar.png',
        'Magma Block':'https://www.minecraftcrafting.info/imgs/craft_magmablock.png',
        'Nether Wart Block':'https://www.minecraftcrafting.info/imgs/craft_netherwartblock.png',
        'Red Nether Brick':'https://www.minecraftcrafting.info/imgs/craft_rednetherbrick.png',
        'Bone Block':'https://www.minecraftcrafting.info/imgs/craft_boneblock.png',
        'Dried Kelp Block':'https://www.minecraftcrafting.info/imgs/craft_driedkelpblock.png',
        'Packed Ice':'https://www.minecraftcrafting.info/imgs/craft_packedice.png',
        'Blue Ice':'https://www.minecraftcrafting.info/imgs/craft_blueice.png',
        'Pickaxes':'https://www.minecraftcrafting.info/imgs/craft_pick.gif',
        'Axes':'https://www.minecraftcrafting.info/imgs/craft_axe.gif',
        'Shovels':'https://www.minecraftcrafting.info/imgs/craft_shovel.gif',
        'Hoes':'https://www.minecraftcrafting.info/imgs/craft_hoe.gif',
        'Fishing Rod':'https://www.minecraftcrafting.info/imgs/craft_fishingrod.png',
        'Flint & Steel':'https://www.minecraftcrafting.info/imgs/craft_flintandsteel.png',
        'Compass':'https://www.minecraftcrafting.info/imgs/craft_compass.png',
        'Clock':'https://www.minecraftcrafting.info/imgs/craft_clock.png',
        'Bucket':'https://www.minecraftcrafting.info/imgs/craft_bucket.png',
        'Shears':'https://www.minecraftcrafting.info/imgs/craft_shears.png',
        'Shulker Box':'https://www.minecraftcrafting.info/imgs/craft_shulkerbox.png',
        'Helmet':'https://www.minecraftcrafting.info/imgs/craft_helmet.gif',
        'Chestplate':'https://www.minecraftcrafting.info/imgs/craft_chestplate.gif',
        'Leggings':'https://www.minecraftcrafting.info/imgs/craft_leggings.gif',
        'Boots':'https://www.minecraftcrafting.info/imgs/craft_boots.gif',
        'Sword':'https://www.minecraftcrafting.info/imgs/craft_sword.gif',
        'Bow':'https://www.minecraftcrafting.info/imgs/craft_bow.png',
        'Arrow':'https://www.minecraftcrafting.info/imgs/craft_arrow.png',
        'Horse Armour':'https://www.minecraftcrafting.info/imgs/craft_horsearmour.png',
        'Shield':'https://www.minecraftcrafting.info/imgs/craft_shield.png',
        'Spectral Arrow':'https://www.minecraftcrafting.info/imgs/craft_spectralarrow.png',
        'Tipped Arrow':'https://www.minecraftcrafting.info/imgs/craft_tippedarrow.png',
        'Conduit':'https://www.minecraftcrafting.info/imgs/craft_conduit.png',
        'Turtle Shell':'https://www.minecraftcrafting.info/imgs/craft_turtleshell.png',
        'Crossbow':'https://www.minecraftcrafting.info/imgs/craft_crossbow.png',
        'Pressure Plates':'https://www.minecraftcrafting.info/imgs/craft_pressureplates.gif',
        'Trapdoor':'https://www.minecraftcrafting.info/imgs/craft_trapdoor.png',
        'Fence Gate':'https://www.minecraftcrafting.info/imgs/craft_fencegate.gif',
        'Button':'https://www.minecraftcrafting.info/imgs/craft_button.gif',
        'Lever':'https://www.minecraftcrafting.info/imgs/craft_lever.gif',
        'Redstone Repeater':'https://www.minecraftcrafting.info/imgs/craft_repeater.gif',
        'Redstone Torch':'https://www.minecraftcrafting.info/imgs/craft_redstonetorch.png',
        'Jukebox':'https://www.minecraftcrafting.info/imgs/craft_jukebox_new.png',
        'Dispenser':'https://www.minecraftcrafting.info/imgs/craft_dispenser.png',
        'Piston':'https://www.minecraftcrafting.info/imgs/craft_piston.png',
        'Sticky Piston':'https://www.minecraftcrafting.info/imgs/craft_stickypiston.png',
        'Minecart':'https://www.minecraftcrafting.info/imgs/craft_minecart.png',
        'Powered Minecart':'https://www.minecraftcrafting.info/imgs/craft_poweredminecart.png',
        'Storage Minecart':'https://www.minecraftcrafting.info/imgs/craft_storageminecart.png',
        'Rail':'https://www.minecraftcrafting.info/imgs/craft_tracks.png',
        'Powered Rail':'https://www.minecraftcrafting.info/imgs/craft_poweredrail.jpg',
        'Detector Rail':'https://www.minecraftcrafting.info/imgs/craft_detectorrail.jpg',
        'Redstone Lamp':'https://www.minecraftcrafting.info/imgs/0craft_redstonelamp.png',
        'Tripwire Hook':'https://www.minecraftcrafting.info/imgs/craft_tripwirehook.png',
        'Activator Rail':'https://www.minecraftcrafting.info/imgs/craft_activatorrail.png',
        'Daylight Sensor':'https://www.minecraftcrafting.info/imgs/craft_daylightsensor.png',
        'Dropper':'https://www.minecraftcrafting.info/imgs/craft_dropper.png',
        'Hopper':'https://www.minecraftcrafting.info/imgs/craft_hopper.png',
        'Minecart with Hopper':'https://www.minecraftcrafting.info/imgs/craft_minecartwithhopper.png',
        'Minecart with TNT':'https://www.minecraftcrafting.info/imgs/craft_minecartwithtnt.png',
        'Redstone Comparator':'https://www.minecraftcrafting.info/imgs/craft_redstonecomparator.png',
        'Trapped Chest':'https://www.minecraftcrafting.info/imgs/craft_trappedchest.png',
        'Weighted Pressure Plates':'https://www.minecraftcrafting.info/imgs/craft_weightedpressureplates.gif',
        'Iron Trapdoor':'https://www.minecraftcrafting.info/imgs/craft_irontrapdoor.png',
        'Observer':'https://www.minecraftcrafting.info/imgs/craft_observer.png',
        'Bowl':'https://www.minecraftcrafting.info/imgs/craft_bowl.png',
        'Mushroom Stew':'https://www.minecraftcrafting.info/imgs/craft_stew.png',
        'Bread':'https://www.minecraftcrafting.info/imgs/craft_bread.png',
        'Golden Apple':'https://www.minecraftcrafting.info/imgs/craft_goldenapple.png',
        'Enchanted Golden Apple':'https://www.minecraftcrafting.info/imgs/craft_enchantedgoldenapple.png',
        'Sugar':'https://www.minecraftcrafting.info/imgs/craft_sugar.png',
        'Cake':'https://www.minecraftcrafting.info/imgs/craft_cake.png',
        'Cookies':'https://www.minecraftcrafting.info/imgs/craft_cookie.png',
        'Melon Block':'https://www.minecraftcrafting.info/imgs/craft_melonblock.png',
        'Melon Seeds':'https://www.minecraftcrafting.info/imgs/craft_melonseeds.png',
        'Pumpkin Seeds':'https://www.minecraftcrafting.info/imgs/craft_pumpkinseeds.png',
        'Golden Carrot':'https://www.minecraftcrafting.info/imgs/craft_goldencarrot.png',
        'Pumpkin Pie':'https://www.minecraftcrafting.info/imgs/craft_pumpkinpie.png',
        'Rabbit Stew':'https://www.minecraftcrafting.info/imgs/craft_rabbitstew.png',
        'Suspicious Stew':'https://www.minecraftcrafting.info/imgs/craft_suspiciousstew.png',
        'Bed':'https://www.minecraftcrafting.info/imgs/craft_bed.png',
        'Painting':'https://www.minecraftcrafting.info/imgs/craft_painting.png',
        'Paper':'https://www.minecraftcrafting.info/imgs/craft_paper.png',
        'Book':'https://www.minecraftcrafting.info/imgs/craft_book_new.png',
        'Book and Quill':'https://www.minecraftcrafting.info/imgs/craft_bookandquill.png',
        'Map':'https://www.minecraftcrafting.info/imgs/craft_map.png',
        'Glass Panes':'https://www.minecraftcrafting.info/imgs/craft_glasspanes.png',
        'Iron Bars':'https://www.minecraftcrafting.info/imgs/craft_ironbars.gif',
        'Gold Ingot':'https://www.minecraftcrafting.info/imgs/craft_goldingot.png',
        'Nether Brick Fence':'https://www.minecraftcrafting.info/imgs/craft_netherbrickfence.png',
        'Eye of Ender':'https://www.minecraftcrafting.info/imgs/craft_eyeofender.png',
        'Enchantment Table':'https://www.minecraftcrafting.info/imgs/craft_enchantmenttable.png',
        'Fire Charge':'https://www.minecraftcrafting.info/imgs/0craft_firecharge.png',
        'Ender Chest':'https://www.minecraftcrafting.info/imgs/craft_enderchest.png',
        'Beacon':'https://www.minecraftcrafting.info/imgs/craft_beacon_new.png',
        'Anvil':'https://www.minecraftcrafting.info/imgs/craft_anvil.png',
        'Flower Pot':'https://www.minecraftcrafting.info/imgs/craft_flowerpot.png',
        'Item Frame':'https://www.minecraftcrafting.info/imgs/craft_itemframe.png',
        'Carrot on a Stick':'https://www.minecraftcrafting.info/imgs/craft_carrotonastick.png',
        'Firework Rocket':'https://www.minecraftcrafting.info/imgs/craft_fireworkrocket.gif',
        'Firework Star':'https://www.minecraftcrafting.info/imgs/craft_fireworkstar.gif',
        'Lead':'https://www.minecraftcrafting.info/imgs/craft_lead.png',
        'Carpets':'https://www.minecraftcrafting.info/imgs/craft_carpets.gif',
        'Stained Glass':'https://www.minecraftcrafting.info/imgs/craft_stainedglass.gif',
        'Leather':'https://www.minecraftcrafting.info/imgs/craft_leather.png',
        'Banner':'https://www.minecraftcrafting.info/imgs/craft_banner.png',
        'Armor Stand':'https://www.minecraftcrafting.info/imgs/craft_armorstand.png',
        'End Rod':'https://www.minecraftcrafting.info/imgs/craft_endrod.png',
        'End Crystal':'https://www.minecraftcrafting.info/imgs/craft_endcrystal.png',
        'Iron Nugget':'https://www.minecraftcrafting.info/imgs/craft_ironnugget.png',
        'Concrete Powder':'https://www.minecraftcrafting.info/imgs/craft_concretepowder.png',
        'Campfire':'https://www.minecraftcrafting.info/imgs/craft_campfire.png',
        'Scaffolding':'https://www.minecraftcrafting.info/imgs/craft_scaffolding.png',
        'Barrel':'https://www.minecraftcrafting.info/imgs/craft_barrel.png',
        'Blast Furnace':'https://www.minecraftcrafting.info/imgs/craft_blastfurnace.png',
        'Smoker':'https://www.minecraftcrafting.info/imgs/craft_smoker.png',
        'Cartography Table':'https://www.minecraftcrafting.info/imgs/craft_cartographytable.png',
        'Composter':'https://www.minecraftcrafting.info/imgs/craft_composter.png',
        'Fletching Table':'https://www.minecraftcrafting.info/imgs/craft_fletchingtable.png',
        'Smithing Table':'https://www.minecraftcrafting.info/imgs/craft_smithingtable.png',
        'Stonecutter':'https://www.minecraftcrafting.info/imgs/craft_stonecutter.png',
        'Grindstone':'https://www.minecraftcrafting.info/imgs/craft_grindstone.png',
        'Lantern':'https://www.minecraftcrafting.info/imgs/craft_lantern.png',
        'Lectern':'https://www.minecraftcrafting.info/imgs/craft_lectern.png',
        'Loom':'https://www.minecraftcrafting.info/imgs/craft_loom.png',
        'Bone Meal':'https://www.minecraftcrafting.info/imgs/craft_bonemeal.png',
        'Light Gray Dye':'https://www.minecraftcrafting.info/imgs/craft_lightgraydye.gif',
        'Gray Dye':'https://www.minecraftcrafting.info/imgs/craft_graydye.png',
        'Rose Red':'https://www.minecraftcrafting.info/imgs/craft_reddye.gif',
        'Orange Dye':'https://www.minecraftcrafting.info/imgs/craft_orangedye.gif',
        'Dandelion Yellow':'https://www.minecraftcrafting.info/imgs/craft_yellowdye.gif',
        'Lime Dye':'https://www.minecraftcrafting.info/imgs/craft_limedye.png',
        'Light Blue Dye':'https://www.minecraftcrafting.info/imgs/craft_lightbluedye.png',
        'Cyan Dye':'https://www.minecraftcrafting.info/imgs/craft_cyandye.png',
        'Purple Dye':'https://www.minecraftcrafting.info/imgs/craft_purpledye.png',
        'Magenta Dye':'https://www.minecraftcrafting.info/imgs/craft_magentadye.gif',
        'Pink Dye':'https://www.minecraftcrafting.info/imgs/craft_pinkdye.gif',
        'White Dye':'https://www.minecraftcrafting.info/imgs/craft_whitedye.gif',
        'Blue Dye':'https://www.minecraftcrafting.info/imgs/craft_bluedye.gif',
        'Brown Dye':'https://www.minecraftcrafting.info/imgs/craft_browndye.png',
        'Black Dye':'https://www.minecraftcrafting.info/imgs/craft_blackdye.gif',
        'Wool':'https://www.minecraftcrafting.info/imgs/craft_wool.png',
        'Light Gray Wool':'https://www.minecraftcrafting.info/imgs/craft_lightgraywool.png',
        'Gray Wool':'https://www.minecraftcrafting.info/imgs/craft_graywool.png',
        'Black Wool':'https://www.minecraftcrafting.info/imgs/craft_blackwool.png',
        'Red Wool':'https://www.minecraftcrafting.info/imgs/craft_redwool.png',
        'Orange Wool':'https://www.minecraftcrafting.info/imgs/craft_orangewool.png',
        'Yellow Wool':'https://www.minecraftcrafting.info/imgs/craft_yellowwool.png',
        'Lime Wool':'https://www.minecraftcrafting.info/imgs/craft_limewool.png',
        'Green Wool':'https://www.minecraftcrafting.info/imgs/craft_greenwool.png',
        'Light Blue Wool':'https://www.minecraftcrafting.info/imgs/craft_lightbluewool.png',
        'Cyan Wool':'https://www.minecraftcrafting.info/imgs/craft_cyanwool.png',
        'Blue Wool':'https://www.minecraftcrafting.info/imgs/craft_bluewool.png',
        'Purple Wool':'https://www.minecraftcrafting.info/imgs/craft_purplewool.png',
        'Magenta Wool':'https://www.minecraftcrafting.info/imgs/craft_magentawool.png',
        'Pink Wool':'https://www.minecraftcrafting.info/imgs/craft_pinkwool.png',
        'Brown Wool':'https://www.minecraftcrafting.info/imgs/craft_brownwool.png',
        'Glass Bottle':'https://www.minecraftcrafting.info/imgs/craft_glassbottle.png',
        'Cauldron':'https://www.minecraftcrafting.info/imgs/craft_cauldron.png',
        'Brewing Stand':'https://www.minecraftcrafting.info/imgs/craft_brewingstand.png',
        'Blaze Powder':'https://www.minecraftcrafting.info/imgs/craft_blazepowder.png',
        'Magma Cream':'https://www.minecraftcrafting.info/imgs/craft_magmacream.png',
        'Fermented Spider Eye':'https://www.minecraftcrafting.info/imgs/craft_fermentedspidereye.png',
        'Glistering Melon':'https://www.minecraftcrafting.info/imgs/craft_glisteringmelon.png',       
    }
    await ctx.author.send(item[choice])


@client.command()
async def list(ctx, page):

    craftinglist = {'1' :['PAGE 1/5', 'Wooden Planks' , 'Sticks', 'Torches', 'Crafting Table', 'Furnace', 'Chest', 'Ladders', 'Fence', 'Boat', 'Wooden Slabs', 'Stone Slabs', 'Sign', 'Doors', 'Wood', 'Glowstone', 'Snow Block', 'TNT', 'Clay Block', 'Brick Block', 'Bookshelf', 'Sandstone Block', 'Smooth Sandstone', 'Decorative Sandstone', 'Note Block', 'Jack-O Lantern', 'Lapis Lazuli Block', 'Diamond Block', 'Gold Block', 'Iron Block', 'Emerald Block', 'Coal Block', 'Stone Brick', 'Wooden Stairs', 'Stone Stairs', 'Cobblestone Wall', 'Block of Redstone', 'Nether Brick', 'Block of Quartz', 'Chiseled Quartz Block', 'Pillar Quartz Block', 'Stained Clay', 'Hay Bale', 'Granite', 'Andesite', 'Diorite'],
    '2': ['PAGE 2/5', 'Polished Granite', 'Polished Andesite', 'Polished Diorite', 'Prismarine', 'Prismarine Bricks', 'Dark Prismarine', 'Sea Lantern', 'Coarse Dirt', 'Slime Block', 'Moss Stone', 'Mossy Stone Brick', 'Chiseled Stone Brick', 'Red Sandstone', 'Smooth Red Sandstone', 'Chiseled Red Sandstone', 'Purpur Block', 'Purpur Pillar', 'Magma Block', 'Nether Wart Block', 'Red Nether Brick', 'Bone Block', 'Dried Kelp Block', 'Packed Ice', 'Blue Ice', 'Pickaxes', 'Axes', 'Shovels', 'Hoes', 'Fishing Rod', 'Flint & Steel', 'Compass', 'Clock', 'Bucket', 'Shears', 'Shulker Box', 'Helmet', 'Chestplate', 'Leggings', 'Boots', 'Sword', 'Bow', 'Arrow', 'Horse Armour', 'Shield', 'Spectral Arrow'],
     '3': ['PAGE 3/5', 'Tipped Arrow', 'Conduit', 'Turtle Shell', 'Crossbow', 'Pressure Plates', 'Trapdoor', 'Fence Gate', 'Button', 'Lever', 'Redstone Repeater', 'Redstone Torch', 'Jukebox', 'Dispenser', 'Piston', 'Sticky Piston', 'Minecart', 'Powered Minecart', 'Storage Minecart', 'Rail', 'Powered Rail', 'Detector Rail', 'Redstone Lamp', 'Tripwire Hook', 'Activator Rail', 'Daylight Sensor', 'Dropper', 'Hopper', 'Minecart with Hopper', 'Minecart with TNT', 'Redstone Comparator', 'Trapped Chest', 'Weighted Pressure Plates', 'Iron Trapdoor', 'Observer', 'Bowl', 'Mushroom Stew', 'Bread', 'Golden Apple', 'Enchanted Golden Apple', 'Sugar', 'Cake', 'Cookies', 'Melon Block', 'Melon Seeds', 'Pumpkin Seeds'],
      '4': ['PAGE 4/5', 'Golden Carrot', 'Pumpkin Pie', 'Rabbit Stew', 'Suspicious Stew', 'Bed', 'Painting', 'Paper', 'Book', 'Book and Quill', 'Map', 'Glass Panes', 'Iron Bars', 'Gold Ingot', 'Nether Brick Fence', 'Eye of Ender', 'Enchantment Table', 'Fire Charge', 'Ender Chest', 'Beacon', 'Anvil', 'Flower Pot', 'Item Frame', 'Carrot on a Stick', 'Firework Rocket', 'Firework Star', 'Lead', 'Carpets', 'Stained Glass', 'Leather', 'Banner', 'Armor Stand', 'End Rod', 'End Crystal', 'Iron Nugget', 'Concrete Powder', 'Campfire', 'Scaffolding', 'Barrel', 'Blast Furnace', 'Smoker', 'Cartography Table', 'Composter', 'Fletching Table', 'Smithing Table'], 
      '5': ['PAGE 5/5', 'Stonecutter', 'Grindstone', 'Lantern', 'Lectern', 'Loom', 'Bone Meal', 'Light Gray Dye', 'Gray Dye', 'Rose Red', 'Orange Dye', 'Dandelion Yellow', 'Lime Dye', 'Light Blue Dye', 'Cyan Dye', 'Purple Dye', 'Magenta Dye', 'Pink Dye', 'White Dye', 'Blue Dye', 'Brown Dye', 'Black Dye', 'Wool', 'Light Gray Wool', 'Gray Wool', 'Black Wool', 'Red Wool', 'Orange Wool', 'Yellow Wool', 'Lime Wool', 'Green Wool', 'Light Blue Wool', 'Cyan Wool', 'Blue Wool', 'Purple Wool', 'Magenta Wool', 'Pink Wool', 'Brown Wool', 'Glass Bottle', 'Cauldron', 'Brewing Stand', 'Blaze Powder', 'Magma Cream', 'Fermented Spider Eye', 'Glistering Melon']}

    await ctx.author.send('\n'.join(craftinglist[page]))
    
    
    


@client.command()
async def clear(ctx, amount=5):
    await ctx.channel.purge(limit=amount)





#@client.event
#async def on_member_join(member):
    #print(f'{member} has joined the server.')


#@client.event
#async def on_member_remove(member):
   # print(f'{member} has left the server.')


client.run()
